### ISSUE TITLE
'Request Resolution Failure' for /hellolib and /gettingstarted 

### ISSUE THREAD

**Issue by boticello** [1060NetKernel/getting-started#1]
I followed the README instructions and everything worked: `http://localhost:8080/getting-started/helloworld` produced **Hello Resource Oriented World**.

I changed to the _hellolib_ and _hellomicroservice_ directories and ran `gradle deployModuleNK`. The builds were successful.

But visiting `http://localhost:8080/getting-started/hellolib` and `http://localhost:8080/getting-started/uppercase?url=http://www.google.com` produced **Request Resolution Failure**.

I followed the request trace but was left none the wiser. Can you help?

**Comment by pjr1060** [comment]
Hi - sorry you hit a snag.  I just verified the following steps work for me (assuming you've cloned the repo and got the helloworld module built and installed and have a copy of NK running).
1. cd to the _hellomicroservice_ module.
2. **gradle build deployModuleNK**    (the trick here is _deployModuleNK_ which tells NK about the newly built module and hot-deploys it to your running instance).
3. Try the link [http://localhost:8080/getting-started/uppercase?url=http://www.google.com](http://localhost:8080/getting-started/uppercase?url=http://www.google.com)  and you should see an upper case version of google.

This assumes NK is already running.  If its not then first just do **gradle startNK**

Follow the same steps for the _hellolib_ module.

Please let me know if this sorts it for you.

**Comment by boticello** [comment]
That worked! Thank you.

My error was that I did not run `gradle build` in the other module directories before running `gradle deployNK` to deploy them. I didn't see an error message to say that the module I was trying to deploy wasn't built.

This explains the **Request Resolution Failure** – the modules were not deployed. And it also explains why I couldn't see them in the Control Panel.

Two suggestions:
1. Warning and/or error messages in the gradle commands to indicate when modules hadn't been built before attempted deployment. 
2. A clarification in the README separating the different commands and explaining them in turn. So –

### Install NetKernel

`gradle installNK`

### Build and deploy a module
1. `gradle build`
2. `gradle deployNK`

Or — `gradle build deployNK`

### Start NetKernel and load the module

`gradle startNK`

### Stop NetKernel

`gradle stopNK`

---

Thanks for the quickstart. I'm super-excited about NetKernel. I'll direct future questions to the mailing list.
